parkingNum: 6
#resolution : 0.005
PL_SIZE: [0.64, 0.66]

PL0: [ 1.25,  0.75]
PL1: [-1.10,  0.75]
PL2: [ 1.25, -0.34]

PL3: [-1.10, -0.38]
PL4: [ 1.25, -1.38]
PL5: [-1.10, -1.38]

MainSpot: [-1.0, 1.5]

OutputSpot: [1.15, 1.5]
InputSpot: [-1.0, 1.5]

LiftingSpot: [-0.82,  0.7]
LiftingSpot_two: [-0.82,  0.05]
