# TARGET_VELOCITY: 0.2
# VELOCITY_RESOLUTION: 0.01
# YAWRATE_RESOLUTION: 0.05
# PREDICT_TIME: 1.8
# TO_GOAL_COST_GAIN: 5.0
# SPEED_COST_GAIN: 1.0
# OBSTACLE_COST_GAIN: 10.0
# ANGLE_RESOLUTION: 0.0087
# MAX_DIST: 10.0
# GOAL_THRESHOLD: 0.3
# TURN_DIRECTION_THRESHOLD: 0.1
# OBOT_FRAME: "base_link"
# MAX_VELOCITY: 0.3
# MIN_VELOCITY: -0.25
# MAX_YAWRATE: 1.0
# # MAX_D_YAWRATE: 5.0
# MAX_D_YAWRATE: 5.0
# MAX_ACCELERATION: 2.0



TARGET_VELOCITY: 0.2
VELOCITY_RESOLUTION: 0.02
YAWRATE_RESOLUTION: 0.02
PREDICT_TIME: 5.0
TO_GOAL_COST_GAIN: 25.0
SPEED_COST_GAIN: 25.0
OBSTACLE_COST_GAIN: 5.0
ANGLE_RESOLUTION: 0.0017
MAX_DIST: 10.0
GOAL_THRESHOLD: 0.1
TURN_DIRECTION_THRESHOLD: 0.1