# ROBOT_FRAME: "base_link"
# MAX_VELOCITY: 0.25
# MIN_VELOCITY: 0.1
# MAX_YAWRATE: 0.6
# MAX_D_YAWRATE: 5.0
# MAX_ACCELERATION: 0.5
OBOT_FRAME: "base_link"
MAX_VELOCITY: 0.2
MIN_VELOCITY: 0
MAX_YAWRATE: 0.5
# MAX_D_YAWRATE: 5.0
MAX_D_YAWRATE: 3.0
MAX_ACCELERATION: 2.0